### ISSUE TITLE
dh init warning: Host does not exist: dinghy

### ISSUE THREAD

**Issue by paulhudson** [chinthakagodawita/docker-hat#23]
##### Issue:

dh init spits warning that dinghy doesn't exist. It's a fresh install, so probably shouldn't assume it would.
##### Reproduce:

After first brew install:

$ dh init
Password:
Error: Host does not exist: dinghy
Error removing machine dinghy: Error: Host does not exist: dinghy
There was an error removing a machine. To force remove it, pass the -f option. Warning: this might leave it running on the provider.
Creating the dinghy VM...
##### Impact:

Minimal
init continued to build successfully.

**Comment by chinthakagodawita** [comment]
Unfortunately that's because we do a `dinghy destroy` as part of the init process to make sure we start from a clean slate.

I can't suppress output because it may prompt for a password as part of the destroy process.

An option may be to prefix that output with the following message:

'Attempting to remove any existing VMs, please ignore any errors...'

**Comment by chinthakagodawita** [comment]
Will be fixed in [Helm](https://github.com/sitback/helm/), closing.
